imports:
  parameter: ./parameter.yml
  http: ./http.yml

types:
  ResourceType:
    enum:
      - API
      - CMS
      - WEBSERVER

  VulnType:
    enum:
      - SQLI
      - XSS
      - SSTI
      - COMMAND_INJECTION

  RunMode:
    enum:
      - FUZZ
      - SCAN

  Config:
    properties:
      targets: list<string>
      threads: integer
      timeout: integer
      proxy: optional<string>
      runMode: RunMode
      scanResourceTypes: optional<list<ResourceType>>
      scanModules: optional<list<string>>
      fuzzVulnTypes: optional<list<VulnType>>
      fuzzParams: optional<list<parameter.Parameter>>
      fuzzMethods: optional<list<http.HttpMethod>>
